stages:
  - test
  - analysis

include:
  - template: Code-Quality.gitlab-ci.yml

junit:
  stage: test
  image: gradle
  script:
    - chmod +x ./gradlew
    - mkdir ./logs
    - ./gradlew test > ./logs/test_logs.log
  artifacts:
    paths:
      - ./logs/test_logs.log
    expire_in: 1 day
    when: on_failure
  only:
    - pushes
    - merge_request
    - master

code_quality:
  stage: analysis
  variables:
    SOURCE_CODE: src/main
  artifacts:
    paths: [ gl-code-quality-report.json ]

